# BUILD.gn - 点菜管理系统编译配置
# 深圳大学鸿蒙南向设备基础课程期末考试 - 试题一
#
# 集成方式：将Answer1_Demo.c/h放入device/qemu/arm_mps2_an386/test/
# 修改test/BUILD.gn包含本文件中的sources和include_dirs
# 修改vendor/ohemu/qemu_mini_system_demo/BUILD.gn添加test:demo依赖

static_library("demo") {
  sources = [
    "Answer1_Demo.c",
    "test_demo.c",
  ]

  include_dirs = [
    ".",
    "//kernel/liteos_m/kernel/include",
    "//kernel/liteos_m/kernel/arch/include",
    "//kernel/liteos_m/utils",
    "//kernel/liteos_m/kal/cmsis",
    "//kernel/liteos_m/components/shell/include",
    "//third_party/bounds_checking_function/include",
    "//utils/native/lite/include",
  ]
}
